# Generated by Django 5.1.3 on 2024-11-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(max_length=255)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('url_visited', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
